- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#FF5297"
  weight: 80
  roles:
    - Magistrat
    - IAA
    - Lawyer
    - NtrOfficer

#- type: department # Surnise-Blueshield
#  id: BlueShield
#  name: department-Blueshield
#  description: department-Blueshield-description
#  color: "#0f4e81"
#  roles:
#    - BlueShieldEnsign
#    - BlueShieldOfficer
#  primary: false
#  weight: 50

- type: department
  id: PlanetPrison
  sort: 0
  name: department-PlanetPrison
  description: department-PlanetPrison-description
  color: "#9f4000"
  roles:
  - HeadOfPrison
  - PrisonPilot
  - PrisonWorker
  - PrisonChef
  - PrisonDoctor
  - PrisonEngineer
  - PrisonGuard
  - PlanetPrisoner
